P(indexPage) =
"<html>"
"<head>"
"	<meta charset=\"utf-8\">"
"	<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\">"
"	<style>"
"	body {"
"		overflow	: hidden;"
"		padding		: 0;"
"		margin		: 0;"
"		background-color: #BBB;"
"	}"
"	.wrapper {"
"	    text-align: center;"
"     margin:150px auto;"
"	}"
"	.button {"
"	    background-color: #4CAF50;"
"	    border: none;"
"	    color: white;"
"	    padding: 15px 32px;"
"	    text-align: center;"
"	    text-decoration: none;"
"	    display: inline-block;"
"	    font-size: 16px;"
"	    margin: 4px 2px;"
"	    cursor: pointer;"
"	}"
"	</style>"
"</head>"
"	<body>"
"		<div class=\"wrapper\">"
"		<button class=\"button\" onClick=\"javascript:window.location.href='/single.html'\">Single Joystick Control</button>"
"		<button class=\"button\" onClick=\"javascript:window.location.href='/dual.html'\">Dual Joystick Control</button>"
"	</div>"
"</body>"
"</html>";

P(dualjsPage) =
"<html>"
"<head>"
"	<meta charset=\"utf-8\">"
"	<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\">"
"	<style>"
"	body {"
"		overflow	: hidden;"
"		padding		: 0;"
"		margin		: 0;"
"		background-color: #BBB;"
"	}"
"	#info {"
"		position	: absolute;"
"		top		: 100px;"
"		width		: 100%;"
"		padding		: 5px;"
"		text-align	: center;"
"	}"
"	#info a {"
"		color		: #66F;"
"		text-decoration	: none;"
"	}"
"	#info a:hover {"
"		text-decoration	: underline;"
"	}"
"	#container {"
"		width		: 100%;"
"		height		: 100%;"
"		overflow	: hidden;"
"		padding		: 0;"
"		margin		: 0;"
"		-webkit-user-select	: none;"
"		-moz-user-select	: none;"
"	}"
"	</style>"
"</head>"
"<body>"
"	<div id=\"container\"></div>"
"	<div id=\"info\">"
"		Dual Joystick Control"
"		<br/>"
"		Touch and GO!"
"		<br/>"
"		<span id=\"result\"></span>"
"	</div>"
"<script src=\"virtualjoystick.js\"></script>"
"<script>"
"	console.log(\"touchscreen is\", VirtualJoystick.touchScreenAvailable() ? \"available\" : \"not available\");"
"	var joystickR	= new VirtualJoystick({"
"		container	: document.body,"
"		strokeStyle	: 'cyan',"
"		limitStickTravel: true,"
"		stickRadius	: 120,"
"   mouseSupport	: true,"
"	});"
"	joystickR.addEventListener('touchStartValidation', function(event){"
"		var touch	= event.changedTouches[0];"
"		if( touch.pageX < window.innerWidth/2 )	return false;"
"		return true"
"	});"
"	var joystickL	= new VirtualJoystick({"
"		container	: document.body,"
"		strokeStyle	: 'orange',"
"		limitStickTravel: true,"
"		stickRadius	: 120,"
"   mouseSupport	: true,"
"	});"
"	joystickL.addEventListener('touchStartValidation', function(event){"
"		var touch	= event.changedTouches[0];"
"		if( touch.pageX >= window.innerWidth/2 )	return false;"
"		return true"
"	});"
"	setInterval(function(){"
"		var outputEl	= document.getElementById('result');"
"   var rCmd = joystickR.deltaY() * (-30);"
"   var lCmd = joystickL.deltaY() * (-30);"
"		outputEl.innerHTML	="
"			' Left:'+ lCmd"
"			+ '<br/>'"
"			+ ' Right:'+ rCmd;"
"    var xhttp;"
"    if (window.XMLHttpRequest) {"
"        xhttp = new XMLHttpRequest();"
"        } else {"
"        xhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");"
"    }"
"    var leftParam = \"LEFT=\" + lCmd;"
"    var rightParam = \"&RIGHT=\" + rCmd;"
"    var encodedURL= \"cmd?\" + leftParam + rightParam;"
"    xhttp.open(\"GET\", encodedURL, true);"
"    xhttp.send();"
"	}, 225);"
"</script></body>"
"</html>";

P(singlejsPage) =
"<html>"
"<head>"
"	<meta charset=\"utf-8\">"
"	<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\">"
"	<style>"
"	body {"
"		overflow	: hidden;"
"		padding		: 0;"
"		margin		: 0;"
"		background-color: #BBB;"
"	}"
"	#info {"
"		position	: absolute;"
"		top		: 100px;"
"		width		: 100%;"
"		padding		: 5px;"
"		text-align	: center;"
"	}"
"	#info a {"
"		color		: #66F;"
"		text-decoration	: none;"
"	}"
"	#info a:hover {"
"		text-decoration	: underline;"
"	}"
"	#container {"
"		width		: 100%;"
"		height		: 100%;"
"		overflow	: hidden;"
"		padding		: 0;"
"		margin		: 0;"
"		-webkit-user-select	: none;"
"		-moz-user-select	: none;"
"	}"
"	</style>"
"</head>"
"<body>"
"	<div id=\"container\"></div>"
"	<div id=\"info\">"
"		Single Joystick Control"
"		<br/>"
"		Touch and GO!"
"		<br/>"
"		<span id=\"result\"></span>"
"	</div>"
"<script src=\"virtualjoystick.js\"></script>"
"<script>"
"	console.log(\"touchscreen is\", VirtualJoystick.touchScreenAvailable() ? \"available\" : \"not available\");"
"  var joystick	= new VirtualJoystick({"
"    container	: document.getElementById('container'),"
"    limitStickTravel: true,"
"    stickRadius	: 120,"
"    mouseSupport	: true,"
"  });"
"  setInterval(function(){"
"    var negate = -1;"
"    var x = (joystick.deltaX()*negate);"
"    var y = (joystick.deltaY()*negate);"
"    var v = (100-Math.abs(x))*(y/100)+y;"
"    var w = (100-Math.abs(y))*(x/100)+x;"
"    if (joystick.down()){"
"      var lCmd = 30*((v+w)/2).toFixed(0);"
"      var rCmd = 30*((v-w)/2).toFixed(0);"
"    } else {"
"      var rCmd = 30*((v+w)/2).toFixed(0);"
"      var lCmd = 30*((v-w)/2).toFixed(0);"
"    }"
"    var outputEl	= document.getElementById('result');"
"    outputEl.innerHTML	= '<b></b> '"
"      + ' Left:'+ lCmd"
"			 + '<br/>'"
"      + ' Right:'+ rCmd;"
"    var xhttp;"
"    if (window.XMLHttpRequest) {"
"        xhttp = new XMLHttpRequest();"
"        } else {"
"        xhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");"
"    }"
"    var leftParam = \"LEFT=\" + lCmd;"
"    var rightParam = \"&RIGHT=\" + rCmd;"
"    var encodedURL= \"cmd?\" + leftParam + rightParam;"
"    xhttp.open(\"GET\", encodedURL, true);"
"    xhttp.send();"
"  }, 225);"
"</script></body>"
"</html>";
